version: "3.3"
services:
  web:
    build: ./front
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    build: ./node_api
    ports:
      - "3001:3001"
      - "3002:3002"
    networks: 
     - network-backend
    volumes:
      - type: bind
        source: /home/mihanich/share/video
        target: /home/mihanich/prod/node_api/video
      - type: bind
        source: /home/mihanich/share/images
        target: /home/mihanich/prod/node_api/images
      - type: bind
        source: /home/mihanich/board/node_api/config
        target: /home/mihanich/prod/node_api/config


networks:
  network-backend:
